pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_PSW = credentials('DOCKERHUB_CREDENTIALS_PSW')
        DOCKERHUB_CREDENTIALS_USR = credentials('DOCKERHUB_CREDENTIALS_USR')
        DOCKER_HUB_REPO = 'mawulidev'  // Replace with your DockerHub username
        REPO_URL = 'https://github.com/winfred-agbotey/java-advance-week4.git'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[url: REPO_URL]],
                        extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'CloneOption', noTags: false, shallow: true, depth: 1]]
                    ])
                }
            }
        }

        stage('Build Modules in Order') {
            steps {
                script {
                    sh '''
                        cd my-microservice-app/
                        ls
                        mvn clean install
                    '''
                }
            }
        }

        stage('Build Docker Images to DockerHub') {
            input {
                message 'Deploy to Production?'
                ok 'Deploy'
            }
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'DOCKERHUB_CREDENTIALS_USR', variable: 'DOCKERHUB_CREDENTIALS_USR'),
                        string(credentialsId: 'DOCKERHUB_CREDENTIALS_PSW', variable: 'DOCKERHUB_CREDENTIALS_PSW')
                    ]) {
                        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'

                        sh 'docker push $DOCKER_HUB_REPO/api:latest'
                        sh 'docker push $DOCKER_HUB_REPO/service:latest'
                        sh 'docker push $DOCKER_HUB_REPO/core:latest'
                        sh 'docker push $DOCKER_HUB_REPO/data-access:latest'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build and Deployment Successful!'
        }
        failure {
            echo 'Build Failed! Check the logs.'
        }
    }
}
